# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EZLoading' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'EZLoadingActivity'

  # Pods for EZLoading

  target 'EZLoadingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EZLoadingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
