# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUseAlamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper'

  # Pods for SwiftUseAlamofire

  target 'SwiftUseAlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUseAlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
