# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToasterSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Toaster'

  # Pods for ToasterSwift

  target 'ToasterSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToasterSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
